apiVersion: apps/v1
kind: Deployment
metadata:
  name: isbg
spec:
  selector:
    matchLabels:
      app: isbg
  template:
    metadata:
      labels:
        app: isbg
    spec:
      volumes:
      - name: spamassassin-data
        persistentVolumeClaim:
            claimName: spamassassin-data
      - name: private-email
        secret:
          secretName: post-at-yannik-mueller.de-config
      containers:
      - name: isbg
        image: ghcr.io/yannik26/docker_isbg:main
        volumeMounts:
        - name: private-email
          mountPath: /var/lib/mailaccounts/post_at_yannik-mueller.de.conf
          subPath: post_at_yannik-mueller.de.conf
          readOnly: true
        - mountPath: "/var/lib/spamassassin/"
          name: spamassassin-data
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        envFrom:
        - configMapRef:
            name: isbg-config
      - name: debian
        image: debian:bookworm-slim
        volumeMounts:
        - name: private-email
          mountPath: /var/lib/mailaccounts/post_at_yannik-mueller.de.conf
          subPath: post_at_yannik-mueller.de.conf
          readOnly: true
        - mountPath: "/var/lib/spamassassin/"
          name: spamassassin-data
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        envFrom:
        - configMapRef:
            name: isbg-config

