apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        imagePullPolicy: Always
        image: harbor.yannikmueller.eu/sds-status/backend:testing
        env: 
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: sds-database-app
              key: uri
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef: 
              name: sds-valkey-valkey-cluster
              key: valkey-password
        envFrom:
        - secretRef:
            name: sds-backend-secret
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: api-svc
spec:
  selector:
    app: backend
  ports:
  - port: 80
    targetPort: 4000
