apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sds-ingress
  labels:
    name: sds-ingress
spec:
  rules:
  - host: funk.yannikmueller.eu
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: <Service>
            port: 
              number: <Port>
