apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: lentencrypt
  name: sds-ingress
  labels:
    name: sds-ingress
spec:
  rules:
  - host: funk.yannikmueller.eu
    http:
      paths:
      - pathType: Prefix
        path: "/leitstelle"
        backend:
          service:
            name: leitstelle-svc
            port: 
              number: 80
      - pathType: Prefix
        path: "/api"
        backend:
          service:
            name: api-svc
            port: 
              number: 80
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: sds-tableau-svc
            port: 
              number: 80
  tls:
  - hosts: 
    - funk.yannikmueller.eu 
    secretName: funk.yannikmueller.eu-tls