apiVersion: v1
kind: Pod
metadata:
  name: psql
spec:
  containers:
  - name: psql
    image: debian:stable-slim
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always