apiVersion: apps/v1
kind: Deployment
metadata:
  name: leitstelle
spec:
  selector:
    matchLabels:
      app: leitstelle
  template:
    metadata:
      labels:
        app: leitstelle
    spec:
      containers:
      - name: leitstelle
        image: harbor.yannikmueller.eu/sds-status/leitstelle:testing
        env:
        - name: SDS_API_URL
          value: funk.yannikmueller.eu
        - name: SDS_OIDC_AUTHORITY
          value: https://sso.yannikmueller.eu/realms/Funk-Status-App
        - name: SDS_OIDC_CLIENT_ID
          value: sds-dev
        - name: SDS_OIDC_REDIRECT
          value: http://funk.yannikmueller.eu/leitstelle/
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: leitstelle-svc
spec:
  selector:
    app: leitstelle
  ports:
  - port: 80
    targetPort: 3000

