apiVersion: apps/v1
kind: Deployment
metadata:
  name: sds-tableau
spec:
  selector:
    matchLabels:
      app: sds-tableau
  template:
    metadata:
      labels:
        app: sds-tableau
    spec:
      containers:
      - name: sds-tableau
        image: harbor.yannikmueller.eu/sds-status/sds-tableau:testing
        env:
        - name: SDS_API_URL
          value: https://funk.yannikmueller.eu
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sds-tableau-svc
spec:
  selector:
    app: sds-tableau
  ports:
  - port: 80
    targetPort: 80
