apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotenberg
spec:
  selector:
    matchLabels:
      app: gotenberg
  template:
    metadata:
      labels:
        app: gotenberg
    spec:
      containers:
      - name: gotenberg
        image: docker.io/gotenberg/gotenberg:8.15.3
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "200m"
        ports:
        - containerPort: 3000
        command: ["gotenberg", "--chromium-disable-javascript=true", "--chromium-allow-list=file:///tmp/.*"]
---
apiVersion: v1
kind: Service
metadata:
  name: gotenberg-svc
spec:
  selector:
    app: gotenberg
  ports:
  - port: 3000
    targetPort: 3000
