apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
spec:
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      volumes:
        - name: redis-pv 
          persistentVolumeClaim:
            claimName: redis-pvc
      containers:
      - name: broker
        image: docker.io/library/redis:7
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 6379
        volumeMounts: 
        - name: redis-pv 
          mountPath: /data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
--- 
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
spec:
  selector:
    app: broker
  ports:
  - port: 6379
    targetPort: 6379



