apiVersion: apps/v1
kind: Deployment
metadata:
  name: tika
spec:
  selector:
    matchLabels:
      app: tika
  template:
    metadata:
      labels:
        app: tika
    spec:
      containers:
      - name: tika
        image: docker.io/apache/tika:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9998
---
apiVersion: v1
kind: Service
metadata:
  name: tika-svc
spec:
  selector:
    app: tika
  ports:
  - port: 9998
    targetPort: 9998

