apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-postgres-cluster
spec:
  instances: 1

  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-user
  storage:
    storageClass: longhorn
    size: 4Gi
