apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-postgres-cluster
spec:
  instances: 1

  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: postgres-user
  storage:
    storageClass: longhorn
    size: 4Gi
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: immich-db
spec:
  name: immich
  owner: immich
  cluster:
    name: immich-postgres-cluster
  extensions:
  - name: vector
