apiVersion: v1
kind: ConfigMap
metadata:
  name: mealie-config
  namespace: mealie
data:
  ALLOW_SIGNUP: "true"
  TZ: Europe/Berlin
  MAX_WORKERS: "1"
  WEB_CONCURRENCY: "1"
  BASE_URL: https://mealie.yannikmueller.eu
  OPENAI_BASE_URL: "http://ollama.ollama.svc.cluster.local:80/v1"
  OPENAI_API_KEY: "none"
  OPENAI_MODEL: phi3.5
  OPENAI_WORKERS: "2"
  OPENAI_SEND_DATABASE_DATA: "true"
  OIDC_AUTH_ENABLED: "true"
  OIDC_SIGNUP_ENABLED: "true"
  OIDC_CONFIGURATION_URL: "https://sso.yannikmueller.eu/realms/Homelab/.well-known/openid-configuration"
  OIDC_CLIENT_ID: "mealie"
  OIDC_PROVIDER_NAME: "Keycloak"
  OIDC_AUTO_REDIRECT: "true"



