apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    keel.sh/policy: major
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@daily"
  name: mealie
  namespace: mealie
  labels:
    app: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
    spec:
      volumes:
        - name: mealie-pv
          persistentVolumeClaim:
            claimName: mealie-pvc
      containers:
      - name: mealie
        image: ghcr.io/mealie-recipes/mealie:v3.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
          name: http-web-svc
        envFrom:
          - configMapRef:
              name: mealie-config
          - secretRef:
              name: mealie-secret
        volumeMounts:
        - mountPath: "/app/data/"
          name: mealie-pv


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-pvc
  namespace: mealie
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
