apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    keel.sh/policy: major
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@daily"
  name: ollama
spec:
  selector:
    matchLabels:
      name: ollama
  template:
    metadata:
      labels:
        name: ollama
    spec:
      volumes:
        - name: ollama-pv
          persistentVolumeClaim:
            claimName: ollama-pvc
      containers:
      - name: ollama
        image: ollama/ollama:0.5.6
        ports:
        - name: http
          containerPort: 11434
          protocol: TCP
        volumeMounts:
        - mountPath: "/root/.ollama/"
          name: ollama-pv
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 25Gi

---
apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: ollama
spec:
  type: ClusterIP
  selector:
    name: ollama
  ports:
  - port: 80
    name: http
    targetPort: http
    protocol: TCP
