apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: hoarder-web
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hoarder-ingress
  # namespace: hoarder
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  #   nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: traefik
  tls:
  - hosts:
      - hoarder.yannikmueller.eu
    secretName: hoarder-tls
  rules:
  - host: "hoarder.yannikmueller.eu"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: web
            port:
              number: 80