apiVersion: v1
kind: Service
metadata:
  name: spoolman-svc
spec:
  selector:
    app: spoolman
  ports:
  - port: 80
    targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spoolman-ingress
  labels:
    name: spoolman-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: traefik
  tls:
  - hosts:
      - spoolman.yannikmueller.eu
    secretName: spoolman-tls
  rules:
  - host: "spoolman.yannikmueller.eu"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: spoolman-svc
            port: 
              number: 80
