apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-database
spec:
  instances: 2
  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak
      secret:
        name: app-secret
  storage:
    storageClass: longhorn
    size: 5Gi
---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: pooler-keycloak-database-rw
spec:
  cluster:
    name: keycloak-database
  instances: 1
  type: rw
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "1000"
      default_pool_size: "10"
      ignore_startup_parameters: "search_path"

