apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gitea-database
spec:
  instances: 1
  bootstrap:
    initdb:
      database: gitea
      owner: gitea
      secret:
        name: gitea-db-secret
  storage:
    storageClass: longhorn
    size: 5Gi
---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: pooler-gitea-database-rw
spec:
  cluster:
    name: gitea-database
  instances: 1
  type: rw
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "1000"
      default_pool_size: "10"
      # ignore_startup_parameters: "search_path"
